# Generated by Django 5.1.4 on 2024-12-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("errands", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("express", "快递"),
                    ("takeaway", "外卖"),
                    ("purchase", "代购"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
