# Generated by Django 5.1.4 on 2024-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("errands", "0005_task_type_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="reward",
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待接取"),
                    ("in_progress", "进行中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="student_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
