# Generated by Django 5.1.4 on 2024-12-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("errands", "0006_user_avatar_alter_task_reward_alter_task_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="reward",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待接取"),
                    ("in_progress", "进行中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("task", "reviewed_by")},
        ),
    ]
