# Generated by Django 5.1.4 on 2024-12-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("errands", "0007_alter_task_reward_alter_task_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="errands.task",
            ),
        ),
    ]
